extends:
  - plugin:@mysticatea/es2015
  - plugin:@mysticatea/+node
globals: {
  root: "off"
}
overrides:
  - files: "**/*.ts"
    plugins:
      - "@typescript-eslint"
    parser: "@typescript-eslint/parser"
    rules:
      "@typescript-eslint/consistent-type-imports": error
      no-duplicate-imports: off
      "@typescript-eslint/no-duplicate-imports": error
  - files: "typings/**"
    rules:
      '@mysticatea/node/no-missing-import':
        - error
        - allowModules:
          - estree

settings:
  node:
    tryExtensions:
      - .ts
      - .js
      - .json
