name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
  - cron: 0 0 * * 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Checkout submodules
      run: git submodule update --init
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install Packages
      run: npm install
    - name: Lint
      run: npm run -s lint

  test:
    name: Test

    strategy:
      matrix:
        eslint: [7, 6, 5]
        node: [14, 12, 12.0, 10, 10.12]
        exclude:
        # Run ESLint 6 on only the latest LTS.
        - node: 14
          eslint: 6
        - node: 12.0
          eslint: 6
        - node: 10
          eslint: 6
        - node: 10.12
          eslint: 6
          # Run ESLint 5 on only the latest LTS.
        - node: 14
          eslint: 5
        - node: 12.0
          eslint: 5
        - node: 10
          eslint: 5
        - node: 10.12
          eslint: 5

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Checkout submodules
      run: git submodule update --init
    - name: Install Node.js v${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install Packages
      run: npm install
    - name: Install ESLint v${{ matrix.eslint }}
      run: |
        if [ ${{ matrix.eslint }} -eq 6 ]; then
          cd test/fixtures/eslint
          npm install
        else
          npm install --no-save eslint@5.16.0
          cd test/fixtures/eslint
          git checkout v5.16.0
          npm install eslint-utils@1.4.0
          npm install
        fi
    - name: Build
      run: npm run -s build
    - name: Test
      run: npm run -s test:mocha
    - name: Send Coverage
      run: npm run -s codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
